In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame


In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['t','u','v'])

ser2 = Series([3,4],index=['x','y'])


In [7]:
ser1

t    0
u    1
v    2
dtype: int64

In [8]:
ser2

x    3
y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

t    0
u    1
v    2
x    3
y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0    1
t  0.0  NaN
u  1.0  NaN
v  2.0  NaN
x  NaN  3.0
y  NaN  4.0

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  t    0
      u    1
      v    2
cat2  x    3
      y    4
dtype: int64

In [21]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['x','y','z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['y','q','x'])

In [22]:
dframe1

x         y         z
0  0.610722  1.116438 -1.080157
1 -0.746097  0.602764  0.851680
2  1.598502 -1.453461 -0.957864
3  0.455850  0.067758  1.752550

In [23]:
dframe2

y         q         x
0  1.009343  0.393139  1.261629
1  1.237445  0.346107  1.064541
2  0.393655 -0.423816 -0.588536

In [24]:
pd.concat([dframe1,dframe2])

q         x         y         z
0       NaN  0.610722  1.116438 -1.080157
1       NaN -0.746097  0.602764  0.851680
2       NaN  1.598502 -1.453461 -0.957864
3       NaN  0.455850  0.067758  1.752550
0  0.393139  1.261629  1.009343       NaN
1  0.346107  1.064541  1.237445       NaN
2 -0.423816 -0.588536  0.393655       NaN

In [25]:
pd.concat([dframe1,dframe2],ignore_index=True)

q         x         y         z
0       NaN  0.610722  1.116438 -1.080157
1       NaN -0.746097  0.602764  0.851680
2       NaN  1.598502 -1.453461 -0.957864
3       NaN  0.455850  0.067758  1.752550
4  0.393139  1.261629  1.009343       NaN
5  0.346107  1.064541  1.237445       NaN
6 -0.423816 -0.588536  0.393655       NaN

In [26]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'