In [2]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([ 0.95644846,  0.65408281, -0.7296944 ,  0.64165464, -1.12253982,
        1.29264326,  1.49700209, -1.31851005,  0.50928686, -0.35518836])

In [9]:
B = np.random.randn(10)
B

array([-0.87711703, -0.2200324 , -2.31700972, -1.33260316, -2.59906487,
       -0.89975961, -1.10884746, -0.36943646,  0.73333353,  0.2419912 ])

In [11]:
#Binary Functions
np.add(A,B)

array([ 0.07933143,  0.4340504 , -3.04670413, -0.69094853, -3.72160469,
        0.39288366,  0.38815463, -1.68794651,  1.24262038, -0.11319716])

In [10]:
np.maximum(A,B)

array([ 0.95644846,  0.65408281, -0.7296944 ,  0.64165464, -1.12253982,
        1.29264326,  1.49700209, -0.36943646,  0.73333353,  0.2419912 ])

In [12]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'

In [13]:
import webbrowser

In [15]:
webbrowser.open(website)

True